site_name: Coloop的个人博客

# 
nav:
  - 首页: index.md
  - 博客:
    - 算法练习: 
      - 练习准备: 算法练习/练习准备.md
      - 数组与前缀和:
        - 二分查找: 算法练习/数组与前缀和/二分查找.md
        - 移除元素: 算法练习/数组与前缀和/移除元素.md
        - 有序数组的平方: 算法练习/数组与前缀和/有序数组的平方.md
        - 长度最小的子数组: 算法练习/数组与前缀和/长度最小的子数组.md
        - 螺旋矩阵 II: 算法练习/数组与前缀和/螺旋矩阵 II.md
        - 区间和: 算法练习/数组与前缀和/区间和.md
        - 开发商购买土地: 算法练习/数组与前缀和/开发商购买土地.md
      - 链表:
        - 移除链表元素: 算法练习/链表/移除链表元素.md
        - 设计链表: 算法练习/链表/设计链表.md
        - 翻转链表: 算法练习/链表/翻转链表.md
        - 两两交换链表中的节点: 算法练习/链表/两两交换链表中的节点.md
        - 删除链表的倒数第n个节点: 算法练习/链表/删除链表的倒数第n个节点.md
        - 链表相交: 算法练习/链表/链表相交.md
        - 环形链表: 算法练习/链表/环形链表.md
      - 栈与队列:
        - 用栈实现队列: 算法练习/栈与队列/用栈实现队列.md
        - 用队列实现栈: 算法练习/栈与队列/用队列实现栈.md
        - 有效的括号: 算法练习/栈与队列/有效的括号.md
        - 字符消消乐: 算法练习/栈与队列/字符消消乐.md
        - 逆波兰表达式: 算法练习/栈与队列/逆波兰表达式.md
        - 滑动窗口最大值: 算法练习/栈与队列/滑动窗口最大值.md
        - 前k个高频元素: 算法练习/栈与队列/前k个高频元素.md
      - 字符串:
        - 翻转字符串: 算法练习/字符串/翻转字符串.md
        - 翻转字符串II: 算法练习/字符串/翻转字符串II.md
        - 替换数字: 算法练习/字符串/替换数字.md
        - 翻转字符串的单词: 算法练习/字符串/翻转字符串的单词.md
        - 右旋字符串: 算法练习/字符串/右旋字符串.md
        - 匹配字符串: 算法练习/字符串/匹配字符串.md
        - 重复的字符串: 算法练习/字符串/重复的字符串.md
      - 哈希表:
        - 有效的字母异位词: 算法练习/哈希表/有效的字母异位词.md
        - 两个数组的交集: 算法练习/哈希表/两个数组的交集.md
        - 快乐数: 算法练习/哈希表/快乐数.md
        - 两数之和: 算法练习/哈希表/两数之和.md
        - 四数相加: 算法练习/哈希表/四数相加.md
        - 赎金信: 算法练习/哈希表/赎金信.md
        - 三数之和: 算法练习/哈希表/三数之和.md
        - 四数之和: 算法练习/哈希表/四数之和.md
        - 统计坏数对的数目: 算法练习/哈希表/统计坏数对的数目.md
      - 二叉树:
        - 二叉树的递归遍历: 算法练习/二叉树/二叉树的递归遍历.md
        - 二叉树的迭代遍历（前后）: 算法练习/二叉树/二叉树的迭代遍历（前后）.md
        - 二叉树的迭代遍历（中）: 算法练习/二叉树/二叉树的迭代遍历（中）.md
        - 二叉树的层序遍历: 算法练习/二叉树/二叉树的层序遍历.md
        - 翻转二叉树: 算法练习/二叉树/翻转二叉树.md
        - 对称二叉树: 算法练习/二叉树/对称二叉树.md
      - 动态规划:
        - 携带研究材料: 算法练习/动态规划/携带研究材料.md
      - 回溯:
        - 组合: 算法练习/回溯/组合.md
        - 组合总和: 算法练习/回溯/组合总和.md
        - 电话号码的字母组合: 算法练习/回溯/电话号码的字母组合.md
        - 组合总和 III: 算法练习/回溯/组合总和 III.md
        - 非递增子序列: 算法练习/回溯/非递增子序列.md
      - 图论:
        - 所有可达路径: 算法练习/图论/所有可达路径.md
        - 寻宝(prim算法): 算法练习/图论/寻宝(prim算法).md
        - 岛屿数量: 算法练习/图论/岛屿数量.md
      - 未分类算法题:
        - A-B数对(哈希): 算法练习/未分类算法题/A-B数对(哈希).md
        - AB交换(字符串匹配): 算法练习/未分类算法题/AB交换(字符串匹配).md
        - Fuction(记忆化搜索): 算法练习/未分类算法题/Fuction(记忆化搜索).md
        - k倍区间(前缀和): 算法练习/未分类算法题/k倍区间(前缀和).md
        - perket(回溯): 算法练习/未分类算法题/perket(回溯).md
        - 保龄球（哈希）: 算法练习/未分类算法题/保龄球（哈希）.md
        - 八皇后（回溯）: 算法练习/未分类算法题/八皇后（回溯）.md
        - 卡伦与咖啡（哈希）: 算法练习/未分类算法题/卡伦与咖啡（哈希）.md
        - 填涂颜色（广搜）: 算法练习/未分类算法题/填涂颜色（广搜）.md
        - 奇怪的电梯（深搜）: 算法练习/未分类算法题/奇怪的电梯（深搜）.md
        - 学籍管理(STL): 算法练习/未分类算法题/学籍管理(STL).md
        - 小苯的区间疑惑（动态规划）: 算法练习/未分类算法题/小苯的区间疑惑（动态规划）.md
        - 幸运草（贪心）: 算法练习/未分类算法题/幸运草（贪心）.md
        - 挖地雷（多起点深搜）: 算法练习/未分类算法题/挖地雷（多起点深搜）.md
        - 接龙数组（动态规划）: 算法练习/未分类算法题/接龙数组（动态规划）.md
        - 数列前缀和（前缀和）: 算法练习/未分类算法题/数列前缀和（前缀和）.md
        - 最大子段和（贪心）: 算法练习/未分类算法题/最大子段和（贪心）.md
        - 木材仓库(STL): 算法练习/未分类算法题/木材仓库(STL).md
        - 螺旋矩阵（边界处理）: 算法练习/未分类算法题/螺旋矩阵（边界处理）.md
        - 训练士兵（贪心）: 算法练习/未分类算法题/训练士兵（贪心）.md
        - 选数（回溯）: 算法练习/未分类算法题/选数（回溯）.md
        - 飞机降落（深搜）: 算法练习/未分类算法题/飞机降落（深搜）.md
    - 算法杂谈:
      - 回溯杂谈: 算法杂谈/backtrack.md
    - 缓存系统:
      - 项目简介: CpCache/项目简介.md
      - LRU算法朴素实现: CpCache/LRU算法朴素实现.md
      - 额外知识: CpCache/额外知识.md
      - 缓存策略: CpCache/缓存策略.md
      - LRU算法: CpCache/LRU算法.md
      - LFU算法: CpCache/LFU算法.md
      - ARC算法: CpCache/ARC算法.md
      - 功能测试: CpCache/功能测试.md
      - 编译运行: CpCache/编译运行.md
      - 一些尾声: CpCache/一些尾声.md

# 主题配置
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: 切换到亮色模式
  features:
    - content.code.copy
    - navigation.top
    - toc.follow
    - navigation.tabs
    - header.fixed        
  icon:
    repo: fontawesome/brands/github

# 
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

plugins:
  - search:
      lang: zh